name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Build and Collect Static Files
        run: |
          npm install
          npm run build  # Adjust this command based on your project setup
          npm run collect-static  # Custom command to collect static files

      - name: Upload views directory to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          deploy_key: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./views  # Adjust this path as needed to match your project structure
          publish_branch: gh-pages
          allow_empty_commit: true

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
